# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: master
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kubernetes.client
from kubernetes.client.models.v1alpha3_pod_scheduling_context_status import V1alpha3PodSchedulingContextStatus  # noqa: E501
from kubernetes.client.rest import ApiException

class TestV1alpha3PodSchedulingContextStatus(unittest.TestCase):
    """V1alpha3PodSchedulingContextStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1alpha3PodSchedulingContextStatus
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kubernetes.client.models.v1alpha3_pod_scheduling_context_status.V1alpha3PodSchedulingContextStatus()  # noqa: E501
        if include_optional :
            return V1alpha3PodSchedulingContextStatus(
                resource_claims = [
                    kubernetes.client.models.v1alpha3/resource_claim_scheduling_status.v1alpha3.ResourceClaimSchedulingStatus(
                        name = '0', 
                        unsuitable_nodes = [
                            '0'
                            ], )
                    ]
            )
        else :
            return V1alpha3PodSchedulingContextStatus(
        )

    def testV1alpha3PodSchedulingContextStatus(self):
        """Test V1alpha3PodSchedulingContextStatus"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
