# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: master
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kubernetes.client
from kubernetes.client.models.v1_pod_status import V1PodStatus  # noqa: E501
from kubernetes.client.rest import ApiException

class TestV1PodStatus(unittest.TestCase):
    """V1PodStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1PodStatus
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kubernetes.client.models.v1_pod_status.V1PodStatus()  # noqa: E501
        if include_optional :
            return V1PodStatus(
                conditions = [
                    kubernetes.client.models.v1/pod_condition.v1.PodCondition(
                        last_probe_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        last_transition_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        message = '0', 
                        reason = '0', 
                        status = '0', 
                        type = '0', )
                    ], 
                container_statuses = [
                    kubernetes.client.models.v1/container_status.v1.ContainerStatus(
                        allocated_resources = {
                            'key' : '0'
                            }, 
                        allocated_resources_status = [
                            kubernetes.client.models.v1/resource_status.v1.ResourceStatus(
                                name = '0', 
                                resources = [
                                    kubernetes.client.models.v1/resource_health.v1.ResourceHealth(
                                        health = '0', 
                                        resource_id = '0', )
                                    ], )
                            ], 
                        container_id = '0', 
                        image = '0', 
                        image_id = '0', 
                        last_state = kubernetes.client.models.v1/container_state.v1.ContainerState(
                            running = kubernetes.client.models.v1/container_state_running.v1.ContainerStateRunning(
                                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                            terminated = kubernetes.client.models.v1/container_state_terminated.v1.ContainerStateTerminated(
                                container_id = '0', 
                                exit_code = 56, 
                                finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                message = '0', 
                                reason = '0', 
                                signal = 56, 
                                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                            waiting = kubernetes.client.models.v1/container_state_waiting.v1.ContainerStateWaiting(
                                message = '0', 
                                reason = '0', ), ), 
                        name = '0', 
                        ready = True, 
                        resources = kubernetes.client.models.v1/resource_requirements.v1.ResourceRequirements(
                            claims = [
                                kubernetes.client.models.v1/resource_claim.v1.ResourceClaim(
                                    name = '0', 
                                    request = '0', )
                                ], 
                            limits = {
                                'key' : '0'
                                }, 
                            requests = {
                                'key' : '0'
                                }, ), 
                        restart_count = 56, 
                        started = True, 
                        state = kubernetes.client.models.v1/container_state.v1.ContainerState(), 
                        user = kubernetes.client.models.v1/container_user.v1.ContainerUser(
                            linux = kubernetes.client.models.v1/linux_container_user.v1.LinuxContainerUser(
                                gid = 56, 
                                supplemental_groups = [
                                    56
                                    ], 
                                uid = 56, ), ), 
                        volume_mounts = [
                            kubernetes.client.models.v1/volume_mount_status.v1.VolumeMountStatus(
                                mount_path = '0', 
                                name = '0', 
                                read_only = True, 
                                recursive_read_only = '0', )
                            ], )
                    ], 
                ephemeral_container_statuses = [
                    kubernetes.client.models.v1/container_status.v1.ContainerStatus(
                        allocated_resources = {
                            'key' : '0'
                            }, 
                        allocated_resources_status = [
                            kubernetes.client.models.v1/resource_status.v1.ResourceStatus(
                                name = '0', 
                                resources = [
                                    kubernetes.client.models.v1/resource_health.v1.ResourceHealth(
                                        health = '0', 
                                        resource_id = '0', )
                                    ], )
                            ], 
                        container_id = '0', 
                        image = '0', 
                        image_id = '0', 
                        last_state = kubernetes.client.models.v1/container_state.v1.ContainerState(
                            running = kubernetes.client.models.v1/container_state_running.v1.ContainerStateRunning(
                                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                            terminated = kubernetes.client.models.v1/container_state_terminated.v1.ContainerStateTerminated(
                                container_id = '0', 
                                exit_code = 56, 
                                finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                message = '0', 
                                reason = '0', 
                                signal = 56, 
                                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                            waiting = kubernetes.client.models.v1/container_state_waiting.v1.ContainerStateWaiting(
                                message = '0', 
                                reason = '0', ), ), 
                        name = '0', 
                        ready = True, 
                        resources = kubernetes.client.models.v1/resource_requirements.v1.ResourceRequirements(
                            claims = [
                                kubernetes.client.models.v1/resource_claim.v1.ResourceClaim(
                                    name = '0', 
                                    request = '0', )
                                ], 
                            limits = {
                                'key' : '0'
                                }, 
                            requests = {
                                'key' : '0'
                                }, ), 
                        restart_count = 56, 
                        started = True, 
                        state = kubernetes.client.models.v1/container_state.v1.ContainerState(), 
                        user = kubernetes.client.models.v1/container_user.v1.ContainerUser(
                            linux = kubernetes.client.models.v1/linux_container_user.v1.LinuxContainerUser(
                                gid = 56, 
                                supplemental_groups = [
                                    56
                                    ], 
                                uid = 56, ), ), 
                        volume_mounts = [
                            kubernetes.client.models.v1/volume_mount_status.v1.VolumeMountStatus(
                                mount_path = '0', 
                                name = '0', 
                                read_only = True, 
                                recursive_read_only = '0', )
                            ], )
                    ], 
                host_ip = '0', 
                host_i_ps = [
                    kubernetes.client.models.v1/host_ip.v1.HostIP(
                        ip = '0', )
                    ], 
                init_container_statuses = [
                    kubernetes.client.models.v1/container_status.v1.ContainerStatus(
                        allocated_resources = {
                            'key' : '0'
                            }, 
                        allocated_resources_status = [
                            kubernetes.client.models.v1/resource_status.v1.ResourceStatus(
                                name = '0', 
                                resources = [
                                    kubernetes.client.models.v1/resource_health.v1.ResourceHealth(
                                        health = '0', 
                                        resource_id = '0', )
                                    ], )
                            ], 
                        container_id = '0', 
                        image = '0', 
                        image_id = '0', 
                        last_state = kubernetes.client.models.v1/container_state.v1.ContainerState(
                            running = kubernetes.client.models.v1/container_state_running.v1.ContainerStateRunning(
                                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                            terminated = kubernetes.client.models.v1/container_state_terminated.v1.ContainerStateTerminated(
                                container_id = '0', 
                                exit_code = 56, 
                                finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                message = '0', 
                                reason = '0', 
                                signal = 56, 
                                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                            waiting = kubernetes.client.models.v1/container_state_waiting.v1.ContainerStateWaiting(
                                message = '0', 
                                reason = '0', ), ), 
                        name = '0', 
                        ready = True, 
                        resources = kubernetes.client.models.v1/resource_requirements.v1.ResourceRequirements(
                            claims = [
                                kubernetes.client.models.v1/resource_claim.v1.ResourceClaim(
                                    name = '0', 
                                    request = '0', )
                                ], 
                            limits = {
                                'key' : '0'
                                }, 
                            requests = {
                                'key' : '0'
                                }, ), 
                        restart_count = 56, 
                        started = True, 
                        state = kubernetes.client.models.v1/container_state.v1.ContainerState(), 
                        user = kubernetes.client.models.v1/container_user.v1.ContainerUser(
                            linux = kubernetes.client.models.v1/linux_container_user.v1.LinuxContainerUser(
                                gid = 56, 
                                supplemental_groups = [
                                    56
                                    ], 
                                uid = 56, ), ), 
                        volume_mounts = [
                            kubernetes.client.models.v1/volume_mount_status.v1.VolumeMountStatus(
                                mount_path = '0', 
                                name = '0', 
                                read_only = True, 
                                recursive_read_only = '0', )
                            ], )
                    ], 
                message = '0', 
                nominated_node_name = '0', 
                phase = '0', 
                pod_ip = '0', 
                pod_i_ps = [
                    kubernetes.client.models.v1/pod_ip.v1.PodIP(
                        ip = '0', )
                    ], 
                qos_class = '0', 
                reason = '0', 
                resize = '0', 
                resource_claim_statuses = [
                    kubernetes.client.models.v1/pod_resource_claim_status.v1.PodResourceClaimStatus(
                        name = '0', 
                        resource_claim_name = '0', )
                    ], 
                start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else :
            return V1PodStatus(
        )

    def testV1PodStatus(self):
        """Test V1PodStatus"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
