# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: master
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kubernetes.client
from kubernetes.client.models.v1alpha1_validating_admission_policy_binding_spec import V1alpha1ValidatingAdmissionPolicyBindingSpec  # noqa: E501
from kubernetes.client.rest import ApiException

class TestV1alpha1ValidatingAdmissionPolicyBindingSpec(unittest.TestCase):
    """V1alpha1ValidatingAdmissionPolicyBindingSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1alpha1ValidatingAdmissionPolicyBindingSpec
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kubernetes.client.models.v1alpha1_validating_admission_policy_binding_spec.V1alpha1ValidatingAdmissionPolicyBindingSpec()  # noqa: E501
        if include_optional :
            return V1alpha1ValidatingAdmissionPolicyBindingSpec(
                match_resources = kubernetes.client.models.v1alpha1/match_resources.v1alpha1.MatchResources(
                    exclude_resource_rules = [
                        kubernetes.client.models.v1alpha1/named_rule_with_operations.v1alpha1.NamedRuleWithOperations(
                            api_groups = [
                                '0'
                                ], 
                            api_versions = [
                                '0'
                                ], 
                            operations = [
                                '0'
                                ], 
                            resource_names = [
                                '0'
                                ], 
                            resources = [
                                '0'
                                ], 
                            scope = '0', )
                        ], 
                    match_policy = '0', 
                    namespace_selector = kubernetes.client.models.v1/label_selector.v1.LabelSelector(
                        match_expressions = [
                            kubernetes.client.models.v1/label_selector_requirement.v1.LabelSelectorRequirement(
                                key = '0', 
                                operator = '0', 
                                values = [
                                    '0'
                                    ], )
                            ], 
                        match_labels = {
                            'key' : '0'
                            }, ), 
                    object_selector = kubernetes.client.models.v1/label_selector.v1.LabelSelector(), 
                    resource_rules = [
                        kubernetes.client.models.v1alpha1/named_rule_with_operations.v1alpha1.NamedRuleWithOperations(
                            scope = '0', )
                        ], ), 
                param_ref = kubernetes.client.models.v1alpha1/param_ref.v1alpha1.ParamRef(
                    name = '0', 
                    namespace = '0', 
                    parameter_not_found_action = '0', 
                    selector = kubernetes.client.models.v1/label_selector.v1.LabelSelector(
                        match_expressions = [
                            kubernetes.client.models.v1/label_selector_requirement.v1.LabelSelectorRequirement(
                                key = '0', 
                                operator = '0', 
                                values = [
                                    '0'
                                    ], )
                            ], 
                        match_labels = {
                            'key' : '0'
                            }, ), ), 
                policy_name = '0', 
                validation_actions = [
                    '0'
                    ]
            )
        else :
            return V1alpha1ValidatingAdmissionPolicyBindingSpec(
        )

    def testV1alpha1ValidatingAdmissionPolicyBindingSpec(self):
        """Test V1alpha1ValidatingAdmissionPolicyBindingSpec"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
