# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: master
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kubernetes.client
from kubernetes.client.models.v1_cluster_trust_bundle_projection import V1ClusterTrustBundleProjection  # noqa: E501
from kubernetes.client.rest import ApiException

class TestV1ClusterTrustBundleProjection(unittest.TestCase):
    """V1ClusterTrustBundleProjection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1ClusterTrustBundleProjection
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kubernetes.client.models.v1_cluster_trust_bundle_projection.V1ClusterTrustBundleProjection()  # noqa: E501
        if include_optional :
            return V1ClusterTrustBundleProjection(
                label_selector = kubernetes.client.models.v1/label_selector.v1.LabelSelector(
                    match_expressions = [
                        kubernetes.client.models.v1/label_selector_requirement.v1.LabelSelectorRequirement(
                            key = '0', 
                            operator = '0', 
                            values = [
                                '0'
                                ], )
                        ], 
                    match_labels = {
                        'key' : '0'
                        }, ), 
                name = '0', 
                optional = True, 
                path = '0', 
                signer_name = '0'
            )
        else :
            return V1ClusterTrustBundleProjection(
                path = '0',
        )

    def testV1ClusterTrustBundleProjection(self):
        """Test V1ClusterTrustBundleProjection"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
