# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: master
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kubernetes.client
from kubernetes.client.models.v1alpha1_lease_candidate_spec import V1alpha1LeaseCandidateSpec  # noqa: E501
from kubernetes.client.rest import ApiException

class TestV1alpha1LeaseCandidateSpec(unittest.TestCase):
    """V1alpha1LeaseCandidateSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1alpha1LeaseCandidateSpec
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kubernetes.client.models.v1alpha1_lease_candidate_spec.V1alpha1LeaseCandidateSpec()  # noqa: E501
        if include_optional :
            return V1alpha1LeaseCandidateSpec(
                binary_version = '0', 
                emulation_version = '0', 
                lease_name = '0', 
                ping_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                preferred_strategies = [
                    '0'
                    ], 
                renew_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else :
            return V1alpha1LeaseCandidateSpec(
                lease_name = '0',
                preferred_strategies = [
                    '0'
                    ],
        )

    def testV1alpha1LeaseCandidateSpec(self):
        """Test V1alpha1LeaseCandidateSpec"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
