# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: master
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kubernetes.client
from kubernetes.client.models.flowcontrol_v1_subject import FlowcontrolV1Subject  # noqa: E501
from kubernetes.client.rest import ApiException

class TestFlowcontrolV1Subject(unittest.TestCase):
    """FlowcontrolV1Subject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test FlowcontrolV1Subject
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kubernetes.client.models.flowcontrol_v1_subject.FlowcontrolV1Subject()  # noqa: E501
        if include_optional :
            return FlowcontrolV1Subject(
                group = kubernetes.client.models.v1/group_subject.v1.GroupSubject(
                    name = '0', ), 
                kind = '0', 
                service_account = kubernetes.client.models.v1/service_account_subject.v1.ServiceAccountSubject(
                    name = '0', 
                    namespace = '0', ), 
                user = kubernetes.client.models.v1/user_subject.v1.UserSubject(
                    name = '0', )
            )
        else :
            return FlowcontrolV1Subject(
                kind = '0',
        )

    def testFlowcontrolV1Subject(self):
        """Test FlowcontrolV1Subject"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
