# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: master
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kubernetes.client
from kubernetes.client.models.v1alpha3_pod_scheduling_context_list import V1alpha3PodSchedulingContextList  # noqa: E501
from kubernetes.client.rest import ApiException

class TestV1alpha3PodSchedulingContextList(unittest.TestCase):
    """V1alpha3PodSchedulingContextList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1alpha3PodSchedulingContextList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kubernetes.client.models.v1alpha3_pod_scheduling_context_list.V1alpha3PodSchedulingContextList()  # noqa: E501
        if include_optional :
            return V1alpha3PodSchedulingContextList(
                api_version = '0', 
                items = [
                    kubernetes.client.models.v1alpha3/pod_scheduling_context.v1alpha3.PodSchedulingContext(
                        api_version = '0', 
                        kind = '0', 
                        metadata = kubernetes.client.models.v1/object_meta.v1.ObjectMeta(
                            annotations = {
                                'key' : '0'
                                }, 
                            creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            deletion_grace_period_seconds = 56, 
                            deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            finalizers = [
                                '0'
                                ], 
                            generate_name = '0', 
                            generation = 56, 
                            labels = {
                                'key' : '0'
                                }, 
                            managed_fields = [
                                kubernetes.client.models.v1/managed_fields_entry.v1.ManagedFieldsEntry(
                                    api_version = '0', 
                                    fields_type = '0', 
                                    fields_v1 = kubernetes.client.models.fields_v1.fieldsV1(), 
                                    manager = '0', 
                                    operation = '0', 
                                    subresource = '0', 
                                    time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                ], 
                            name = '0', 
                            namespace = '0', 
                            owner_references = [
                                kubernetes.client.models.v1/owner_reference.v1.OwnerReference(
                                    api_version = '0', 
                                    block_owner_deletion = True, 
                                    controller = True, 
                                    kind = '0', 
                                    name = '0', 
                                    uid = '0', )
                                ], 
                            resource_version = '0', 
                            self_link = '0', 
                            uid = '0', ), 
                        spec = kubernetes.client.models.v1alpha3/pod_scheduling_context_spec.v1alpha3.PodSchedulingContextSpec(
                            potential_nodes = [
                                '0'
                                ], 
                            selected_node = '0', ), 
                        status = kubernetes.client.models.v1alpha3/pod_scheduling_context_status.v1alpha3.PodSchedulingContextStatus(
                            resource_claims = [
                                kubernetes.client.models.v1alpha3/resource_claim_scheduling_status.v1alpha3.ResourceClaimSchedulingStatus(
                                    name = '0', 
                                    unsuitable_nodes = [
                                        '0'
                                        ], )
                                ], ), )
                    ], 
                kind = '0', 
                metadata = kubernetes.client.models.v1/list_meta.v1.ListMeta(
                    continue = '0', 
                    remaining_item_count = 56, 
                    resource_version = '0', 
                    self_link = '0', )
            )
        else :
            return V1alpha3PodSchedulingContextList(
                items = [
                    kubernetes.client.models.v1alpha3/pod_scheduling_context.v1alpha3.PodSchedulingContext(
                        api_version = '0', 
                        kind = '0', 
                        metadata = kubernetes.client.models.v1/object_meta.v1.ObjectMeta(
                            annotations = {
                                'key' : '0'
                                }, 
                            creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            deletion_grace_period_seconds = 56, 
                            deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            finalizers = [
                                '0'
                                ], 
                            generate_name = '0', 
                            generation = 56, 
                            labels = {
                                'key' : '0'
                                }, 
                            managed_fields = [
                                kubernetes.client.models.v1/managed_fields_entry.v1.ManagedFieldsEntry(
                                    api_version = '0', 
                                    fields_type = '0', 
                                    fields_v1 = kubernetes.client.models.fields_v1.fieldsV1(), 
                                    manager = '0', 
                                    operation = '0', 
                                    subresource = '0', 
                                    time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                ], 
                            name = '0', 
                            namespace = '0', 
                            owner_references = [
                                kubernetes.client.models.v1/owner_reference.v1.OwnerReference(
                                    api_version = '0', 
                                    block_owner_deletion = True, 
                                    controller = True, 
                                    kind = '0', 
                                    name = '0', 
                                    uid = '0', )
                                ], 
                            resource_version = '0', 
                            self_link = '0', 
                            uid = '0', ), 
                        spec = kubernetes.client.models.v1alpha3/pod_scheduling_context_spec.v1alpha3.PodSchedulingContextSpec(
                            potential_nodes = [
                                '0'
                                ], 
                            selected_node = '0', ), 
                        status = kubernetes.client.models.v1alpha3/pod_scheduling_context_status.v1alpha3.PodSchedulingContextStatus(
                            resource_claims = [
                                kubernetes.client.models.v1alpha3/resource_claim_scheduling_status.v1alpha3.ResourceClaimSchedulingStatus(
                                    name = '0', 
                                    unsuitable_nodes = [
                                        '0'
                                        ], )
                                ], ), )
                    ],
        )

    def testV1alpha3PodSchedulingContextList(self):
        """Test V1alpha3PodSchedulingContextList"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
